/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaixarRouteImport } from './routes/baixar'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBaixarRouteImport } from './routes/api/public/baixar'

const BaixarRoute = BaixarRouteImport.update({
  id: '/baixar',
  path: '/baixar',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBaixarRoute = ApiPublicBaixarRouteImport.update({
  id: '/api/public/baixar',
  path: '/api/public/baixar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/baixar': typeof BaixarRoute
  '/api/public/baixar': typeof ApiPublicBaixarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/baixar': typeof BaixarRoute
  '/api/public/baixar': typeof ApiPublicBaixarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/baixar': typeof BaixarRoute
  '/api/public/baixar': typeof ApiPublicBaixarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agendamento' | '/baixar' | '/api/public/baixar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agendamento' | '/baixar' | '/api/public/baixar'
  id: '__root__' | '/' | '/agendamento' | '/baixar' | '/api/public/baixar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  BaixarRoute: typeof BaixarRoute
  ApiPublicBaixarRoute: typeof ApiPublicBaixarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/baixar': {
      id: '/baixar'
      path: '/baixar'
      fullPath: '/baixar'
      preLoaderRoute: typeof BaixarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/baixar': {
      id: '/api/public/baixar'
      path: '/api/public/baixar'
      fullPath: '/api/public/baixar'
      preLoaderRoute: typeof ApiPublicBaixarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  BaixarRoute: BaixarRoute,
  ApiPublicBaixarRoute: ApiPublicBaixarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
